name: dna-methyl
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - _openmp_mutex=4.5=2_gnu
  - _py-xgboost-mutex=2.0=cpu_0
  - alembic=1.14.1=pyhd8ed1ab_0
  - anyio=4.8.0=pyhd8ed1ab_0
  - argon2-cffi=23.1.0=pyhd8ed1ab_1
  - argon2-cffi-bindings=21.2.0=py39ha55e580_5
  - arrow=1.3.0=pyhd8ed1ab_1
  - asttokens=3.0.0=pyhd8ed1ab_1
  - async-lru=2.0.4=pyhd8ed1ab_1
  - attrs=25.1.0=pyh71513ae_0
  - aws-c-auth=0.8.1=hd11252f_0
  - aws-c-cal=0.8.1=h099ea23_3
  - aws-c-common=0.10.6=h2466b09_0
  - aws-c-compression=0.3.0=h099ea23_5
  - aws-c-event-stream=0.5.0=h85d8506_11
  - aws-c-http=0.9.2=h3888f84_4
  - aws-c-io=0.15.3=hc5a9e45_6
  - aws-c-mqtt=0.11.0=h2c94728_12
  - aws-c-s3=0.7.9=h6a47413_1
  - aws-c-sdkutils=0.2.2=h099ea23_0
  - aws-checksums=0.2.2=h099ea23_4
  - aws-crt-cpp=0.29.9=he488853_2
  - aws-sdk-cpp=1.11.489=h7d73209_0
  - babel=2.17.0=pyhd8ed1ab_0
  - beautifulsoup4=4.13.3=pyha770c72_0
  - black=25.1.0=py39hcbf5309_0
  - bleach=6.2.0=pyh29332c3_4
  - bleach-with-css=6.2.0=h82add2a_4
  - blosc=1.21.6=hfd34d9b_1
  - bokeh=3.4.2=pyhd8ed1ab_0
  - brotli=1.1.0=h2466b09_2
  - brotli-bin=1.1.0=h2466b09_2
  - brotli-python=1.1.0=py39ha51f57c_2
  - bzip2=1.0.8=h2466b09_7
  - c-ares=1.34.4=h2466b09_0
  - c-blosc2=2.15.2=h9e57077_1
  - ca-certificates=2025.2.25=haa95532_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.18.2=h5782bbf_1
  - catboost=1.2.7=py39h7090721_1
  - certifi=2025.1.31=pyhd8ed1ab_0
  - cffi=1.17.1=py39ha55e580_0
  - charset-normalizer=3.4.1=pyhd8ed1ab_0
  - click=8.1.8=pyh7428d3b_0
  - cloudpickle=3.1.1=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - colorlog=6.9.0=pyh7428d3b_1
  - comm=0.2.2=pyhd8ed1ab_1
  - contourpy=1.3.0=py39h2b77a98_2
  - cpython=3.9.21=py39hd8ed1ab_1
  - cuda-version=11.8=h70ddcb2_3
  - cudatoolkit=11.8.0=h09e9e62_13
  - cycler=0.12.1=pyhd8ed1ab_1
  - cytoolz=1.0.1=py39ha55e580_0
  - dask=2024.8.0=pyhd8ed1ab_0
  - dask-core=2024.8.0=pyhd8ed1ab_0
  - dask-expr=1.1.10=pyhd8ed1ab_0
  - debugpy=1.8.12=py39ha51f57c_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - distributed=2024.8.0=pyhd8ed1ab_0
  - double-conversion=3.3.1=he0c23c2_0
  - eli5=0.13.0=pyhd8ed1ab_0
  - exceptiongroup=1.2.2=pyhd8ed1ab_1
  - executing=2.1.0=pyhd8ed1ab_1
  - flake8=7.1.2=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h765892d_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.56.0=py39hf73967f_0
  - fqdn=1.5.1=pyhd8ed1ab_1
  - freetype=2.12.1=hdaf720e_2
  - fribidi=1.0.10=h8d14728_0
  - fsspec=2025.2.0=pyhd8ed1ab_0
  - future=1.0.0=pyhd8ed1ab_2
  - getopt-win32=0.1=hcfcfb64_1
  - graphite2=1.3.13=h63175ca_1003
  - graphviz=12.2.1=hf40819d_1
  - greenlet=3.1.1=py39ha51f57c_1
  - gts=0.7.6=h6b5321d_4
  - h11=0.14.0=pyhd8ed1ab_1
  - h2=4.2.0=pyhd8ed1ab_0
  - h5py=3.13.0=nompi_py39h0b25466_100
  - harfbuzz=10.3.0=h9e37d49_0
  - hdf5=1.14.3=nompi_hb2c4d47_109
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.7=pyh29332c3_1
  - httpx=0.28.1=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - hyperopt=0.2.7=pyhd8ed1ab_1
  - icu=75.1=he0c23c2_0
  - idna=3.10=pyhd8ed1ab_1
  - imbalanced-learn=0.12.4=pyhd8ed1ab_0
  - importlib-resources=6.5.2=pyhd8ed1ab_0
  - importlib_metadata=8.6.1=hd8ed1ab_0
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - iniconfig=2.0.0=pyhd8ed1ab_1
  - intel-openmp=2024.2.1=h57928b3_1083
  - ipykernel=6.29.5=pyh4bbf305_0
  - ipython=8.18.1=pyh7428d3b_3
  - ipywidgets=8.1.5=pyhd8ed1ab_1
  - isoduration=20.11.0=pyhd8ed1ab_1
  - isort=6.0.1=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.5=pyhd8ed1ab_0
  - joblib=1.4.2=pyhd8ed1ab_1
  - json5=0.10.0=pyhd8ed1ab_1
  - jsonpointer=3.0.0=py39hcbf5309_1
  - jsonschema=4.23.0=pyhd8ed1ab_1
  - jsonschema-specifications=2024.10.1=pyhd8ed1ab_1
  - jsonschema-with-format-nongpl=4.23.0=hd8ed1ab_1
  - jupyter-lsp=2.2.5=pyhd8ed1ab_1
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.7.2=pyh5737063_1
  - jupyter_events=0.12.0=pyh29332c3_0
  - jupyter_server=2.15.0=pyhd8ed1ab_0
  - jupyter_server_terminals=0.5.3=pyhd8ed1ab_1
  - jupyterlab=4.3.5=pyhd8ed1ab_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_2
  - jupyterlab_server=2.27.3=pyhd8ed1ab_1
  - jupyterlab_widgets=3.0.13=pyhd8ed1ab_1
  - khronos-opencl-icd-loader=2024.10.24=h2466b09_1
  - kiwisolver=1.4.7=py39h2b77a98_0
  - krb5=1.21.3=hdf4eb48_0
  - lcms2=2.17=hbcf6048_0
  - lerc=4.0.0=h63175ca_0
  - libabseil=20240722.0=cxx17_h4eb7d71_4
  - libaec=1.1.3=h63175ca_0
  - libarrow=19.0.1=he9da57d_0_cuda
  - libarrow-acero=19.0.1=h7d8d6a5_0_cuda
  - libarrow-dataset=19.0.1=h7d8d6a5_0_cuda
  - libarrow-substrait=19.0.1=h3dbecdf_0_cuda
  - libblas=3.9.0=31_h641d27c_mkl
  - libboost=1.84.0=hb0986bb_7
  - libbrotlicommon=1.1.0=h2466b09_2
  - libbrotlidec=1.1.0=h2466b09_2
  - libbrotlienc=1.1.0=h2466b09_2
  - libcblas=3.9.0=31_h5e41251_mkl
  - libclang13=19.1.7=default_ha5278ca_1
  - libcrc32c=1.1.2=h0e60522_0
  - libcurl=8.12.1=h88aaa65_0
  - libdeflate=1.23=h9062f6e_0
  - libevent=2.1.12=h3671451_1
  - libexpat=2.6.4=he0c23c2_0
  - libffi=3.4.6=h537db12_0
  - libgcc=14.2.0=h1383e82_2
  - libgd=2.3.3=h7208af6_11
  - libglib=2.82.2=h7025463_1
  - libgomp=14.2.0=h1383e82_2
  - libgoogle-cloud=2.35.0=h95c5cb2_0
  - libgoogle-cloud-storage=2.35.0=he5eb982_0
  - libgrpc=1.67.1=h0ac93cb_2
  - libhwloc=2.11.2=default_ha69328c_1001
  - libiconv=1.18=h135ad9c_1
  - libintl=0.22.5=h5728263_3
  - libjpeg-turbo=3.0.0=hcfcfb64_1
  - liblapack=3.9.0=31_h1aa476e_mkl
  - liblightgbm=4.6.0=cpu_hb4e115d_0
  - liblzma=5.6.4=h2466b09_0
  - libparquet=19.0.1=ha850022_0_cuda
  - libpng=1.6.47=had7236b_0
  - libprotobuf=5.28.3=h8309712_1
  - libre2-11=2024.07.02=h4eb7d71_2
  - libsodium=1.0.20=hc70643c_0
  - libsqlite=3.49.1=h67fdade_1
  - libssh2=1.11.1=he619c9f_0
  - libthrift=0.21.0=hbe90ef8_0
  - libtiff=4.7.0=h797046b_3
  - libutf8proc=2.10.0=hf9b99b7_0
  - libwebp-base=1.5.0=h3b0e114_0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca=h57928b3_9
  - libxcb=1.17.0=h0e4246c_0
  - libxgboost=2.1.4=cpu_h0649c51_0
  - libxml2=2.13.6=he286e8c_0
  - libxslt=1.1.39=h3df6e99_0
  - libzlib=1.3.1=h2466b09_2
  - lightgbm=4.6.0=cpu_py_0
  - llvmlite=0.43.0=py39he94c479_1
  - locket=1.0.0=pyhd8ed1ab_0
  - lz4=4.3.3=py39h5c904fa_2
  - lz4-c=1.10.0=h2466b09_1
  - mako=1.3.9=pyhd8ed1ab_0
  - markupsafe=3.0.2=py39hf73967f_1
  - matplotlib=3.9.4=py39hcbf5309_0
  - matplotlib-base=3.9.4=py39h5376392_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - mccabe=0.7.0=pyhd8ed1ab_1
  - mistune=3.1.2=pyhd8ed1ab_0
  - mkl=2024.2.2=h66d3029_15
  - msgpack-python=1.1.0=py39h2b77a98_0
  - munkres=1.0.7=py_1
  - mypy_extensions=1.0.0=pyha770c72_1
  - narwhals=1.27.1=pyhd8ed1ab_0
  - nbclient=0.10.2=pyhd8ed1ab_0
  - nbconvert-core=7.16.6=pyh29332c3_0
  - nbformat=5.10.4=pyhd8ed1ab_1
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - networkx=3.2.1=pyhd8ed1ab_0
  - notebook=7.3.2=pyhd8ed1ab_0
  - notebook-shim=0.2.4=pyhd8ed1ab_1
  - numba=0.60.0=py39h5dcb127_0
  - numexpr=2.10.2=mkl_py39h633a001_0
  - numpy=1.26.4=py39hddb5d58_0
  - opencl-headers=2024.10.24=he0c23c2_0
  - openjpeg=2.5.3=h4d64b90_0
  - openssl=3.4.1=ha4e3fda_0
  - optuna=4.2.1=pyhd8ed1ab_0
  - orc=2.0.3=haf104fe_2
  - overrides=7.7.0=pyhd8ed1ab_1
  - packaging=24.2=pyhd8ed1ab_2
  - pandas=2.2.3=py39h2366fc2_2
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - pango=1.56.1=h286b592_0
  - parso=0.8.4=pyhd8ed1ab_1
  - partd=1.4.2=pyhd8ed1ab_0
  - pathspec=0.12.1=pyhd8ed1ab_1
  - patsy=1.0.1=pyhd8ed1ab_1
  - pcre2=10.44=h3d7b363_2
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=11.1.0=py39h73ef694_0
  - pip=25.0=py39haa95532_0
  - pixman=0.44.2=had0cd8c_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_2
  - platformdirs=4.3.6=pyhd8ed1ab_1
  - plotly=6.0.0=pyhd8ed1ab_0
  - pluggy=1.5.0=pyhd8ed1ab_1
  - prometheus_client=0.21.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.50=pyha770c72_0
  - psutil=7.0.0=py39ha55e580_0
  - pthread-stubs=0.4=h0e40799_1002
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - py-cpuinfo=9.0.0=pyhd8ed1ab_1
  - py-xgboost=2.1.4=cpu_pyh43b6f25_0
  - py4j=0.10.9.9=pyhd8ed1ab_0
  - pyarrow=19.0.1=py39hcbf5309_0
  - pyarrow-core=19.0.1=py39h0b3d880_0_cuda
  - pyarrow-hotfix=0.6=pyhd8ed1ab_1
  - pycodestyle=2.12.1=pyhd8ed1ab_1
  - pycparser=2.22=pyh29332c3_1
  - pyflakes=3.2.0=pyhd8ed1ab_1
  - pygments=2.19.1=pyhd8ed1ab_0
  - pyparsing=3.2.1=pyhd8ed1ab_0
  - pyside6=6.8.2=py39h0285922_1
  - pysocks=1.7.1=pyh09c184e_7
  - pytables=3.9.2=py39h2499b97_3
  - pytest=8.3.4=pyhd8ed1ab_1
  - python=3.9.21=h8205438_1
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python-fastjsonschema=2.21.1=pyhd8ed1ab_0
  - python-graphviz=0.20.3=pyh91182bf_2
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-tzdata=2025.1=pyhd8ed1ab_0
  - python_abi=3.9=2_cp39
  - pytz=2024.1=pyhd8ed1ab_0
  - pywin32=307=py39ha51f57c_3
  - pywinpty=2.0.15=py39ha51f57c_0
  - pyyaml=6.0.2=py39hf73967f_2
  - pyzmq=26.2.1=py39h03e5c00_0
  - qhull=2020.2=hc790b64_5
  - qt6-main=6.8.2=h1259614_0
  - re2=2024.07.02=haf4117d_2
  - referencing=0.36.2=pyh29332c3_0
  - requests=2.32.3=pyhd8ed1ab_1
  - rfc3339-validator=0.1.4=pyhd8ed1ab_1
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rpds-py=0.23.1=py39ha6b3726_0
  - scikit-learn=1.6.1=py39hdd013cc_0
  - scipy=1.13.1=py39h1a10956_0
  - seaborn=0.13.2=hd8ed1ab_3
  - seaborn-base=0.13.2=pyhd8ed1ab_3
  - send2trash=1.8.3=pyh5737063_1
  - setuptools=75.8.0=py39haa95532_0
  - shap=0.46.0=cuda118py39h41a74d8_1
  - singledispatch=3.6.1=pyh44b312d_0
  - six=1.17.0=pyhd8ed1ab_0
  - slicer=0.0.8=pyhd8ed1ab_0
  - snappy=1.2.1=h500f7fa_1
  - sniffio=1.3.1=pyhd8ed1ab_1
  - sortedcontainers=2.4.0=pyhd8ed1ab_1
  - soupsieve=2.5=pyhd8ed1ab_1
  - sqlalchemy=2.0.38=py39ha55e580_0
  - sqlite=3.45.3=h2bbff1b_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - statsmodels=0.14.4=py39h4b0a98a_0
  - tabulate=0.9.0=pyhd8ed1ab_2
  - tblib=3.0.0=pyhd8ed1ab_1
  - terminado=0.18.1=pyh5737063_0
  - threadpoolctl=3.5.0=pyhc1e730c_0
  - tinycss2=1.4.0=pyhd8ed1ab_0
  - tk=8.6.13=h5226925_1
  - tomli=2.2.1=pyhd8ed1ab_1
  - toolz=1.0.0=pyhd8ed1ab_1
  - tornado=6.4.2=py39ha55e580_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - types-python-dateutil=2.9.0.20241206=pyhd8ed1ab_0
  - typing-extensions=4.12.2=hd8ed1ab_1
  - typing_extensions=4.12.2=pyha770c72_1
  - typing_utils=0.1.0=pyhd8ed1ab_1
  - tzdata=2025a=h04d1e81_0
  - ucrt=10.0.22621.0=h57928b3_1
  - unicodedata2=16.0.0=py39ha55e580_0
  - uri-template=1.3.0=pyhd8ed1ab_1
  - urllib3=2.3.0=pyhd8ed1ab_0
  - vc=14.42=haa95532_4
  - vc14_runtime=14.42.34433=h6356254_24
  - vs2015_runtime=14.42.34433=hfef2bbc_24
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - webcolors=24.11.1=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_3
  - websocket-client=1.8.0=pyhd8ed1ab_1
  - wheel=0.45.1=py39haa95532_0
  - widgetsnbextension=4.0.13=pyhd8ed1ab_1
  - win_inet_pton=1.1.0=pyh7428d3b_8
  - winpty=0.4.3=4
  - xgboost=2.1.4=cpu_pyhc1a9e11_0
  - xorg-libice=1.1.2=h0e40799_0
  - xorg-libsm=1.2.5=h0e40799_0
  - xorg-libx11=1.8.11=hf48077a_0
  - xorg-libxau=1.0.12=h0e40799_0
  - xorg-libxdmcp=1.1.5=h0e40799_0
  - xorg-libxext=1.3.6=h0e40799_0
  - xorg-libxpm=3.5.17=h0e40799_1
  - xorg-libxt=1.3.1=h0e40799_0
  - xyzservices=2025.1.0=pyhd8ed1ab_0
  - yaml=0.2.5=h8ffe710_2
  - zeromq=4.3.5=ha9f60a1_7
  - zict=3.0.0=pyhd8ed1ab_1
  - zipp=3.21.0=pyhd8ed1ab_1
  - zlib-ng=2.2.4=hbb528cf_0
  - zstandard=0.19.0=py39ha55989b_0
  - zstd=1.5.7=hbeecb71_1
  - pip:
      - absl-py==2.1.0
      - adjusttext==1.3.0
      - aiohappyeyeballs==2.4.6
      - aiohttp==3.11.13
      - aiohttp-cors==0.7.0
      - aiohttp-retry==2.9.1
      - aiosignal==1.3.2
      - altair==5.5.0
      - amqp==5.3.1
      - anndata==0.10.9
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - appdirs==1.4.4
      - array-api-compat==1.11
      - astunparse==1.6.3
      - async-timeout==5.0.1
      - asyncssh==2.20.0
      - atpublic==5.1
      - bamnostic==1.1.10
      - bayesian-optimization==2.0.3
      - billiard==4.2.1
      - blinker==1.9.0
      - bs4==0.0.2
      - cachetools==5.5.2
      - celery==5.4.0
      - click-didyoumean==0.3.1
      - click-plugins==1.1.1
      - click-repl==0.3.0
      - colorcet==3.1.0
      - colorful==0.5.6
      - configobj==5.0.9
      - cryptography==44.0.1
      - dash==2.18.2
      - dash-core-components==2.0.0
      - dash-html-components==2.0.0
      - dash-table==5.0.0
      - databricks-sdk==0.44.1
      - deprecated==1.2.18
      - dictdiffer==0.9.0
      - diskcache==5.6.3
      - distlib==0.3.9
      - distro==1.9.0
      - docker==7.1.0
      - docker-pycreds==0.4.0
      - dpath==2.2.0
      - dulwich==0.22.7
      - dvc==3.59.1
      - dvc-data==3.16.9
      - dvc-http==2.32.0
      - dvc-objects==5.1.0
      - dvc-render==1.0.2
      - dvc-studio-client==0.21.0
      - dvc-task==0.40.2
      - entrypoints==0.4
      - episcanpy==0.4.0
      - et-xmlfile==2.0.0
      - eval-type-backport==0.2.2
      - filelock==3.17.0
      - flask==3.0.3
      - flatbuffers==25.2.10
      - flatten-dict==0.4.2
      - flufl-lock==8.1.0
      - frozenlist==1.5.0
      - funcy==2.0
      - gast==0.6.0
      - get-annotations==0.1.2
      - gitdb==4.0.12
      - gitpython==3.1.44
      - google-api-core==2.24.1
      - google-auth==2.38.0
      - google-pasta==0.2.0
      - googleapis-common-protos==1.68.0
      - grandalf==0.8
      - graphene==3.4.3
      - graphql-core==3.2.6
      - graphql-relay==3.2.0
      - grpcio==1.70.0
      - gto==1.7.2
      - harmonypy==0.0.10
      - holoviews==1.20.1
      - hvplot==0.11.2
      - hydra-core==1.3.2
      - importlib-metadata==8.5.0
      - interlap==0.2.7
      - intervaltree==3.1.0
      - iterative-telemetry==0.0.10
      - itsdangerous==2.2.0
      - keras==3.8.0
      - kneed==0.8.5
      - kombu==5.4.2
      - legacy-api-wrap==1.4.1
      - libclang==18.1.1
      - linkify-it-py==2.0.3
      - lxml==5.3.1
      - markdown==3.7
      - markdown-it-py==3.0.0
      - mdit-py-plugins==0.4.2
      - mdurl==0.1.2
      - methylcheck==0.8.5
      - methylize==1.1.1
      - methylprep==1.7.1
      - methylsuite==1.4.0
      - mizani==0.11.4
      - ml-dtypes==0.4.1
      - mlflow==2.20.3
      - mlflow-skinny==2.20.3
      - multidict==6.1.0
      - namex==0.0.8
      - natsort==8.4.0
      - omegaconf==2.3.0
      - opencensus==0.11.4
      - opencensus-context==0.1.3
      - openpyxl==3.1.5
      - opentelemetry-api==1.30.0
      - opentelemetry-sdk==1.30.0
      - opentelemetry-semantic-conventions==0.51b0
      - opt-einsum==3.4.0
      - optree==0.14.0
      - orjson==3.10.15
      - panel==1.4.5
      - param==2.2.0
      - plotnine==0.13.6
      - propcache==0.3.0
      - proto-plus==1.26.0
      - protobuf==5.29.3
      - py-spy==0.4.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.1
      - pycombat==0.20
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pydot==3.0.4
      - pygit2==1.15.1
      - pygtrie==2.5.0
      - pymysql==1.1.1
      - pynndescent==0.5.13
      - pyviz-comms==3.0.4
      - ray==2.43.0
      - retrying==1.3.4
      - rich==13.9.4
      - rsa==4.9
      - ruamel-yaml==0.18.10
      - ruamel-yaml-clib==0.2.12
      - scanpy==1.10.3
      - scmrepo==3.3.10
      - semver==3.0.4
      - sentry-sdk==2.22.0
      - session-info==1.0.0
      - setproctitle==1.3.5
      - setuptools-scm==8.2.0
      - shellingham==1.5.4
      - shortuuid==1.0.13
      - shtab==1.7.1
      - smart-open==7.1.0
      - smmap==5.0.2
      - sqlparse==0.5.3
      - sqltrie==0.11.2
      - stdlib-list==0.11.1
      - tbb==2022.0.0
      - tcmlib==1.2.0
      - tensorboard==2.18.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.18.0
      - tensorflow-intel==2.18.0
      - tensorflow-io-gcs-filesystem==0.31.0
      - termcolor==2.5.0
      - tomlkit==0.13.2
      - toolshed==0.4.6
      - typer==0.15.2
      - uc-micro-py==1.0.3
      - umap-learn==0.5.7
      - vine==5.1.0
      - virtualenv==20.29.2
      - voluptuous==0.15.2
      - waitress==3.0.2
      - wandb==0.19.7
      - werkzeug==3.0.6
      - wrapt==1.17.2
      - xlsxwriter==3.2.2
      - yarl==1.18.3
      - yellowbrick==1.5
      - zc-lockfile==3.0.post1
prefix: C:\Users\Bruce\.conda\envs\dna-methyl
